[server]
hostname = "localhost"
port = 8000

[database]
host = "localhost"
port = 28017
dbName = "testDB"
userGroupCollection = "userGroup"
userNotificationsCollection = "userNotifications"
groupNotificationsCollection = "groupNotifications"
createdAtTTL = "10 mins"

[altair]
altairEndpointURL = "/altair"
altairBaseURL = '/altair/'
graphQLEndpointURL = '/graphql'
graphQLSubscriptionsEndpoint = 'ws://localhost:8000/graphql'
